project:
  type: website

website:
  title: "Hayden Krushel's Portfolio"
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
        
      - section:
        text: "GIS Projects"
        href: gis.qmd
        contents:
          - text: "Mapping My Diocese"
            href: episcopal.qmd
          
      - section: 
        text: "Photography"
        href: photography.qmd
        contents:
         - text: "Architecture"
           href: architecture.qmd
         - text: "Streetscape"
           href: streetscape.qmd
         - text: "Landscape"
           href: landscape.qmd
        
format:
  html:
    code-fold: true
    theme:
      - cosmo
      - brand
    mainfont: "Verdana"
    css: styles.css
    toc: true
editor: visual

