---
title: "Mapping My Diocese"
format: html
jupyter: python3
---
TO DO:
Fix CSV by adding possession in names, general EC website for churches without websites


Page Order:
1. The Diocese [1]
2. Geography of the Diocese [2]
3. Where are the Churches [3] + 
4. History of the Diocese
5. Where are the People [4]
6. Church Coverage [5]
7. Changing Populations [6]
8. Gaps in Service [7]
8. Census Data [8]

Maps to add:
General map of the Diocese showing major cities, roads, land features (static) [1]
Topo map (static) [2]
Map of census districts by population (static) [4]
Buffer map of distance from Episcopal churches (static) [5]
Population change by census tract (percent and absolute) (static) [6]
Suitability analysis combining distance from church and higher population census tracts (static) [7]

General interactive map (interactive) [3]
Demographic characteristics by census tract (interactive)



```{python}
import geopandas as gpd
import folium
import leafmap.foliumap as leafmap
from folium.plugins import Search

churches_file = "data/cny_churches_2026.geojson"
counties_file = "data/cny_diocese_counties.geojson"

churches_gdf = gpd.read_file(churches_file)
counties_gdf = gpd.read_file(counties_file)

m = leafmap.Map(
    center=[42.45, -76.5],
    zoom=9,
    width="70%",
    height="700px",
)
m.add_basemap("ROADMAP")

# Add counties
counties = folium.GeoJson(
    counties_gdf,
    name="Counties",
    style_function=lambda feature: {
        "fillColor": "#3388ff",
        "fillOpacity": 0.10,
        "color": "#555555",
        "weight": 1,
    },
    interactive=False,
)
counties.add_to(m)

# Add churches as actual map markers
churches = folium.GeoJson(
    churches_gdf.to_json(),
    name="Diocese of Central NY Churches",
    popup=folium.GeoJsonPopup(
        fields=[
            "Name",
            "Address",
            "County",
            "Website",
        ],
        aliases=[
            "Church:",
            "Address:",
            "County:",
            "Website:",
        ],
        localize=True,
        labels=True,
    ),
    tooltip=folium.GeoJsonTooltip(
        fields=["Name"],
        aliases=["Church:"],
    ),
    marker = folium.CircleMarker(
        radius=7,
        color="white",
        weight=2,
        fill=True,
        fill_color="blue",
        fill_opacity=0.9,
    )
)
churches.add_to(m)

# Search the same layer
Search(
    layer=churches,
    search_label="Address_Search",
    geom_type="Point",
    placeholder="Search name or addresses...",
    collapsed=False,
    position="topleft",
    search_zoom=15,
).add_to(m)

m
```